language: en

pipeline:
- name: WhitespaceTokenizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 8
- name: RegexEntityExtractor
- name: DIETClassifier
  epochs: 100
  use_lookup_tables: true
  case_sensitive: false
- name: FallbackClassifier
  threshold: 0.3

policies:
- name: TEDPolicy
  max_history: 5
  epochs: 100
  validation_split: 0.2
- name: MemoizationPolicy
- name: RulePolicy
  core_fallback_threshold: 0.3
  enable_fallback_prediction: true

session_config:
  session_expiration_time: 10
assistant_id: 20250218-214812-celeste-protagonist
